default_language_version:
  python: python3.12

repos:
  #
  # Python
  #

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0a3
    hooks:
      - id: isort

  #
  # Markdown linting
  #

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.48.0
  #   hooks:
  #     - id: markdownlint

  #
  # Markdown link checking
  #

  # - repo: https://github.com/tcort/markdown-link-check
  #   rev: v3.14.2
  #   hooks:
  #     - id: markdown-link-check

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
